extends:
  - airbnb
  - prettier
  - prettier/react

plugins:
  - prettier

parser: babel-eslint

settings:
  ecmascript: 6

env:
  browser: true

rules:
  react/jsx-filename-extension: 0
  react/forbid-prop-types: 0
  react/destructuring-assignment: 0
  no-param-reassign: 0
  react/sort-comp: 0
  prefer-destructuring: 0
  prettier/prettier: ['error', { 'trailingComma': 'es5', 'singleQuote': true, 'printWidth': 120 }]
